version: "3.7"
services:
    app:
        build: "./app"  # Corrected typo here from 'bulid' to 'build'
        container_name: "app"
        restart: always
        ports:
            - "80:3030"
        environment:
            - mongo_uri=mongodb://root:pass@mongo:27017/mernblog?authSource=admin&retryWrites=true
        depends_on:
            - "mongo"

    mongo:
        image: "mongo"
        container_name: "mongo"
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=pass  # Corrected from USERNAME to PASSWORD
        ports:
            - "27017:27017"
        volumes:
            - type: bind
              source: ./volumes/db
              target: /data/db